setImmediate(()=>{
    console.log("1")
    setTimeout(()=>{
        setImmediate(()=>{
            console.log("2")
        })
        console.log("3")
    },1000)
})
process.nextTick(()=>{
    console.log("4")
    setTimeout(()=>{
        console.log("5")
    },1000)
})
console.log("welcome")